# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
    test:
      docker:
        - image: circleci/android:api-28-alpha  # gcloud is baked into this image
      steps:
        - run:
            name: Build debug APK and release APK
            command: |
              ./gradlew clean build