# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    test:
      docker:
        - image: circleci/android:api-28-alpha  
      steps:
        - run:
            name: Build debug APK and release APK
            command: |
            ./gradlew :app:assembleDebug